# Generated by Django 3.1 on 2020-08-18 13:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200818_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='invalid_product_id', message='Product ID Should be atleast 8 characters', regex='^\\d{8,}*$')]),
        ),
    ]
